### ISSUE TITLE
bytestring-0.12 support

### ISSUE THREAD

**Issue by ysangkok** [kazu-yamamoto/http2#103]
http2 and warp were removed from Stackage Nightly because http2 doesn't support bytestring-0.12. Would be nice to add this.

See https://github.com/commercialhaskell/stackage/pull/7224/files#diff-9949098b9af80e5fcef9a718fdda416f3fa8272ca8add4d67ae65fe892990939R7412

**Comment by kazu-yamamoto** [comment]
http2 v5.0.1 is released to allow bytestrng 0.12.
