### ISSUE TITLE
Trailer support

### ISSUE THREAD

**Issue by cstrahan** [kazu-yamamoto/http2#11]
After a cursory study of the API, I'm not sure how to send [Trailers](https://tools.ietf.org/html/rfc7230#section-4.1.2) (assuming there currently is support). I'd like to implement a [gRPC](www.grpc.io) library for Haskell, and [the protocol](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md) requires support for reading and sending trailers. In Go, this might look something like ([from the docs](https://golang.org/pkg/net/http/#ResponseWriter)):

```go
package main

import (
	"io"
	"net/http"
)

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("/sendstrailers", func(w http.ResponseWriter, req *http.Request) {
		// Before any call to WriteHeader or Write, declare
		// the trailers you will set during the HTTP
		// response. These three headers are actually sent in
		// the trailer.
		w.Header().Set("Trailer", "AtEnd1, AtEnd2")
		w.Header().Add("Trailer", "AtEnd3")

		w.Header().Set("Content-Type", "text/plain; charset=utf-8") // normal header
		w.WriteHeader(http.StatusOK)

		w.Header().Set("AtEnd1", "value 1")
		io.WriteString(w, "This HTTP response has both headers before this text and trailers at the end.\n")
		w.Header().Set("AtEnd2", "value 2")
		w.Header().Set("AtEnd3", "value 3") // These will appear as trailers.
	})
}
```

There's also a [`TrailerPrefix` constant](https://godoc.org/golang.org/x/net/http2#pkg-constants):

> ```go
> const TrailerPrefix = "Trailer:"
> ```
> 
> TrailerPrefix is a magic prefix for ResponseWriter.Header map keys that, if present, signals that the map entry is actually for the response trailers, and not the response headers. The prefix is stripped after the ServeHTTP call finishes and the values are sent in the trailers.
> 
> This mechanism is intended only for trailers that are not known prior to the headers being written. If the set of trailers is fixed or known before the header is written, the normal Go trailers mechanism is preferred:

Does this library support sending Trailers, and if so, would you mind pointing me in the right direction, please?

**Comment by cstrahan** [comment]
Oh, I realize now that I probably want to be looking in `wai`...

**Comment by cstrahan** [comment]
Yep, wasn't looking hard enough -- my apologies!

https://hackage.haskell.org/package/wai-3.0.5.0/docs/Network-Wai-HTTP2.html

**Comment by kazu-yamamoto** [comment]
Yes, it's Warp's job. Unfortunately, however, you are looking at obsoleted Wai/Warp code.

Currently, trailers are not supported. Please open an issue here: https://github.com/yesodweb/wai/issues
And let's discuss what kind of APIs are necessary.

Also, please give a look at this article: http://www.yesodweb.com/blog/2016/07/http2-server-push

It's nice if we can extend `HTTP2Data` to support trailers.

**Comment by cstrahan** [comment]
@kazu-yamamoto Thanks - I've opened an issue here: https://github.com/yesodweb/wai/issues/566
