### ISSUE TITLE
weird errors related to `WINDOW_SIZE` updates

### ISSUE THREAD

**Issue by MangoIV** [kazu-yamamoto/http2#121]
when updating from http2 4.1.4 -> 5.2.2 I started encountering occasional failures with this error message: 
```
StreamErrorIsSent FlowControlError 1 "window update for stream 1 is overflow"
```
There's some weird things in the log where it tries to increase the upper bound of the window by `2^31-1`. 

I have tried trouble shooting it but I haven't had any luck reproducing it with a small example but it looks like maybe it's related to an endianness bug. 

I'm at a bit of a loss here. I was looking at whether it might have been `nginx` modifying `http2` frames but I'd be very surprised if that would be the case. 

Do you have any ideas of where I could start trouble shooting? 
What code actually *picks* which size to upgrade the window by? 
What would happen if the window upper bound would actually reach `maxBound @Int`, is there any logic to reset the window size? 

Thank you so much in advance for any pointers!

**Comment by MangoIV** [comment]
I have already tried the patches submitted by @edsko in `http-semantics` and they unfortunately do not fix my issues.

**Comment by kazu-yamamoto** [comment]
Where does this error occurs? The client side or the server side?
And please tell me the CPU architecture of that side.

**Comment by MangoIV** [comment]
It is x86_64-linux - I will check whether it only occurs on one side tomorrow and report here :)

**Comment by kazu-yamamoto** [comment]
Please check if the size of `Int` is 8 in both side:

```
ghci> import Foreign.Storable 
ghci> sizeOf (1 :: Int)
8
```

**Comment by MangoIV** [comment]
it should be `8` on both the Receiver and Sender as I can reproduce it even if they're running on the same machine; I think the error itself  actually occurs when receiving but only after the sender does the update of the window size to `2^31 - 1`, example: 

```
increased window size by: 2147418112
current window size: 2147483645
current limit: 2147483647
current sent: 2
stream id: 0

increased window size by: 2147418111
current window size: 2147680253
current limit: 2147680255
current sent: 2
stream id: 1
 
updating peer settings:
old window size 262144
new window size 65536
difference -196608
 
increased window size by: -196608
current window size: 2147483645
current limit: 2147483647
current sent: 2
stream id: 1

-- here we would see the error showing up in the logs
```

the update of the peer settings happens in the sender. I don't know what exactly triggers the increase of the window size by `2^31 - 1 - currentSent`, so it would be nice if you perhaps have a pointer at the code which cares for calculating of how much the Sender is going to increase the window size by.

Thank you so much!

**Comment by kazu-yamamoto** [comment]
First of all, you should read the documentation of https://hackage.haskell.org/package/network-control-0.1.0/docs/Network-Control.html

**Comment by MangoIV** [comment]
I of course did but I couldn't see anything that would be terribly suspicious wrt my problem.

**Comment by kazu-yamamoto** [comment]
I will try to implement a feature to transfer big data in `util/h2-client` and `util/h3-client` to reproduce this issue.

**Comment by kazu-yamamoto** [comment]
adb6b61in `main` provides this feature:

First, run `h2c-server`:

```
% h2c-server 127.0.0.1 8080
```

Then, run `h2c-client`:

```
h2c-client 127.0.0.1 8080 -t 10000000000
Throughput 6070.49 Mbps (10000000000 bytes in 12568 msecs)
```

Unfortunately I cannot reproduce your problem.

**Comment by edsko** [comment]
FWIW, we are also hunting a bug, we're getting segfaults in a particular test (or sometimes bus error), and we _believe_ it's got something to do with the write buffer. We'll continue digging and let you know. It may or may not be related to the window update problem, I'm unsure.

**Comment by MangoIV** [comment]
@kazu-yamamoto I am pretty sure that it has nothing to do with sending a lot of data but with doing window updates to the max bound concurrently. It’s not reproducing in all cases but only in some concurrent scenarios. We have a hunch at what it could be but we can only confirm next week.

**Comment by kazu-yamamoto** [comment]
@MangoIV That sounds that `http-semantics` introduces critical sections. Uhhhm.

**Comment by kazu-yamamoto** [comment]
51cfe543043ecc2d5cc63bc7d88d57a02369bf3c introduces concurrency:

```
% h2c-client 127.0.0.1 80 -t 1000000000 / / / / / / / / / / / /
Throughput 797.14 Mbps (1000000000 bytes in 9571 msecs)
Throughput 797.05 Mbps (1000000000 bytes in 9572 msecs)
Throughput 797.05 Mbps (1000000000 bytes in 9572 msecs)
Throughput 796.97 Mbps (1000000000 bytes in 9573 msecs)
Throughput 796.97 Mbps (1000000000 bytes in 9573 msecs)
Throughput 796.97 Mbps (1000000000 bytes in 9573 msecs)
Throughput 796.89 Mbps (1000000000 bytes in 9574 msecs)
Throughput 796.89 Mbps (1000000000 bytes in 9574 msecs)
Throughput 796.89 Mbps (1000000000 bytes in 9574 msecs)
Throughput 796.89 Mbps (1000000000 bytes in 9574 msecs)
Throughput 796.89 Mbps (1000000000 bytes in 9574 msecs)
Throughput 796.89 Mbps (1000000000 bytes in 9574 msecs)
```

Paths are dummy.
I cannot reproduce the issue yet.

**Comment by kazu-yamamoto** [comment]
@MangoIV If you could identify which version introduce your issue, it would be highly helpful.

**Comment by MangoIV** [comment]
I can bisect on Monday if we’re hitting a dead end - thank you so much for your help :)

**Comment by MangoIV** [comment]
so the outcome is as follows - I won't be able to work on this issue anymore (except for maybe in my free time) as we have decided to prioritize removing our use of http2 client, this is what I found in the meanwhile; the situation is as follows: 

- the http/2 client is http2, the http/2 server is nginx 
- we're talking via `tls` to nginx, the protocol negotiation happens via ALPN
- it seems as though the following things then happen: 
  - nginx 
   updates the window size to `2^31 - 1` by sending a `WINDOW_UPDATE` frame, assuming the default window size

**Comment by MangoIV** [comment]
additionally, I'm very sorry for not being able to be able to actually bisect - each rebuild takes ~ 1 hour, I think if I can write a reproducer, I will be able to actually do the bisection effectively.

**Comment by FinleyMcIlwaine** [comment]
FWIW, [the recent patch in http-semantics](https://github.com/kazu-yamamoto/http-semantics/pull/3) solved the segfault that @edsko mentioned above, but does not help with this issue according to @MangoIV.

**Comment by MangoIV** [comment]
It’s possible that it may help - but I’m doubtful, it doesn’t seem very related, the traffic in wireshark actually does look weird and http2 actually does disagree with what nginx and wireshark are seeing. I can try nonetheless.

**Comment by MangoIV** [comment]
I have tried out a patch together with some other long shots wrt improving atomicity but that didn't do it.

**Comment by kazu-yamamoto** [comment]
@MangoIV Could you give me a pcap file (taken by `tcpdump` or so) and its key log file?
I need to understand details.

**Comment by kazu-yamamoto** [comment]
I'm beginning to understand the situation.
@MangoIV If you specify the following `settings` to your client, does your issue disappear?

```haskell
defaultClientConfig { settings = defaultSettings { initialWindowSize = 65535} }
```

**Comment by MangoIV** [comment]
I’m pretty sure it would, yes, without testing.

**Comment by kazu-yamamoto** [comment]
>   - nginx immediately updates the window size to `2^31 - 1` by sending a `WINDOW_UPDATE` frame, assuming the default window size 

I guess that this is *connection* TX for client (sid == 0 is for connection). This is good.

>   - http2 client starts setting up the window size to its standard window size (the 2^18 constant in the http2 library) and after that processes the window update

This is *stream* RX for client.

>   - the window update is too large as http2 client assumes 2^18 as the current window size 

- Stream RX for client is now 2^18.
- Stream TX for client is 2^16 -1 (if server does not specify in Settings).
- WindowUpdate from server should be added to stream TX for client. So, something is wrong.

**Comment by kazu-yamamoto** [comment]
The initial *connection* TX for client cannot be modified by server at the beginning.
The initial value is fixed to 64K.
WindowUpdate from server only can change it.

**Comment by kazu-yamamoto** [comment]
2^18 is RX for client. 
WindowUpdate (2^31 -1 -2^16 + 1) from server is TX for client.
They must not be added together.

**Comment by kazu-yamamoto** [comment]
OK. I understand. My `settings` is also set to peer's `settings` with `IORef` in `newContext`. That's bad.

**Comment by MangoIV** [comment]
Thank you so much for taking so much time for this, this is really, really nice :) 

Should I add some more information? E.g. how wireshark sees it when the thing crashes or logs?

**Comment by kazu-yamamoto** [comment]
I will push one commit very soon.
It would be nice if you could test it.

**Comment by MangoIV** [comment]
sure, I will do that! Thank you so much <3

**Comment by kazu-yamamoto** [comment]
branch: https://github.com/kazu-yamamoto/http2/tree/peer-initial-window-size
commit: 80921ad15fac05715ede7063d57585d4e7049f99

This should fix your issue.

**Comment by MangoIV** [comment]
@kazu-yamamoto but this is just setting to `64K`, right? does this fix the issue or is it just a workaround? I.e. I have trouble to understand whether having `200k` would be a legal `initialWindowSize`.

**Comment by kazu-yamamoto** [comment]
>  but this is just setting to 64K, right? does this fix the issue or is it just a workaround? I.e. I have trouble to understand whether having 200k would be a legal initialWindowSize.

This is a complete fix, not workaround.
You can change `initialWindowSize` in `Settings` as you like and "window update for stream 1 is overflow" should not happen.

**Comment by MangoIV** [comment]
Alright, thank you - I guess I will try it out then. I have a couple of what I suspect to be chesterton's fences - e.g. for some atomicity things - that I have encountered and I would like to ask you questions about them, should I open an extra issue for that?

**Comment by kazu-yamamoto** [comment]
> Perhaps this is the issue though - in my tests the SETTINGS frame that would notify the server about the changed initial window size didn't show up, I thought this was just a timing issue but if we don't ever send a SETTINGS frame upon changing the setting, then we probably have the root of the issue? Does that sound correct?

I confirmed that initialWindowSize is announced from a client.

**Comment by kazu-yamamoto** [comment]
> Alright, thank you - I guess I will try it out then. I have a couple of what I suspect to be chesterton's fences - e.g. for some atomicity things - that I have encountered and I would like to ask you questions about them, should I open an extra issue for that?

Yes, please open new issues.
I will try to help you.

**Comment by MangoIV** [comment]
lovely, thank you so much <3

**Comment by MangoIV** [comment]
thank you for the patch, I think that fixes it!

**Comment by kazu-yamamoto** [comment]
Thank you so much!

**Comment by kazu-yamamoto** [comment]
A new version has been released.
