### ISSUE TITLE
Build failure in http2-5.2.0

### ISSUE THREAD

**Issue by phadej** [kazu-yamamoto/http2#128]
With GHC-9.8.2 and `index-state: 2024-07-01T17:26:19Z`

```
Network/HTTP2/H2/Sender.hs:160:50: error: [GHC-83865]
    • Couldn't match expected type: WindowSize -> IO Next
                  with actual type: IO Next
    • The function ‘curr’ is applied to three value arguments,
```

**Comment by phadej** [comment]
The affected versions seems to be `http2-5.2.0` and `http2-5.2.1`.

**Comment by phadej** [comment]
This is caused by https://github.com/kazu-yamamoto/http-semantics/issues/7. The `5.2.2` and up has bounds on `http-semantics`.

**Comment by phadej** [comment]
I made revisions
- https://hackage.haskell.org/package/http2-5.2.1/revisions/
- https://hackage.haskell.org/package/http2-5.2.0/revisions/

Please, always use upper bounds. I see no upper bounds on `bytestring`, `text`, `vector`, `unordered-containers`. This all are ticking bombs. Figuring out dependency issues for packages like `warp` is very time consuming.

**Comment by kazu-yamamoto** [comment]
@phadej Thank you for pointing this out and for making the revisions.

For `bytestring` and others, I have a dilemma.
They sometime bump major versions but these changes does not effect my packages at all.
I need to change their upper boundaries repeatedly.
I feel that it is time wasting.
That's why I removed their upper boundaries.

**Comment by phadej** [comment]
> They sometime bump major versions but these changes does not effect my packages at all.

The `text-1.2.0.0` was released in 2014, since then only two major releases (to  be fair, in past 3 years thouhg). `bytestring-0.10.0.0` was released in 2012, with two major releases since then (in past 4 years).

> I need to change their upper boundaries repeatedly.

This is perception, not a reality. You won't spend any extra time, if you do those when e.g. update CI to add new GHC major release.
