### ISSUE TITLE
Versions < 5.3.4 don't build with `http-semantics-0.2.1`

### ISSUE THREAD

**Issue by sol** [kazu-yamamoto/http2#144]
This results in build errors, e.g. https://github.com/hspec/sensei/actions/runs/10623493127/job/29450019815?pr=127#step:8:986.

1. I think technically, `http-semantics` would have required a major  version bump.  However, it's too late for that. So let's  ignore that.
2. I think versions of `http2 < 5.3.4` need hackage revisions to constrain `http-semantics` to `< 0.2.1`.

**Comment by kazu-yamamoto** [comment]
My bad. Sorry for your inconvenience.
I have set `http-semantics < 0.2.1` to `http2 5.3.3` on Hackage.
If you think this should be done also for other versions, please let me know.

**Comment by sol** [comment]
Thank you @kazu-yamamoto.  I think versions [5.3.0](https://hackage.haskell.org/package/http2-5.3.0), [5.3.1](https://hackage.haskell.org/package/http2-5.3.1), [5.3.2](https://hackage.haskell.org/package/http2-5.3.2) need this as well.

**Comment by kazu-yamamoto** [comment]
If so, I would like to deprecate http-semantics 0.2.1 and provide http-semantics 0.3.
What do you think?

**Comment by sol** [comment]
I think adding the upper bounds on `http2` is easier and more robust.

**Comment by kazu-yamamoto** [comment]
Done for the three versions.

**Comment by sol** [comment]
Great👍
