### ISSUE TITLE
Unexpected "Thread killed by timeout manager" in 5.3.6

### ISSUE THREAD

**Issue by edsko** [kazu-yamamoto/http2#153]
I'm seeing threads die with "Thread killed by timeout manager" in 5.3.6, but not in 5.3.5 or 5.3.4. Apologies for not noticing this sooner (when we discussed #151); I had missed it because our main test suite did not catch this error, only our stress tests do. This feels like a regression of #136 / #137, but I do not know for sure. I will dig and let you know.

**Comment by edsko** [comment]
It's possible that this is related to #150.

**Comment by kazu-yamamoto** [comment]
Ah, I'm sure that this is relating to ef79679.
We should not re-throw the asynchronous exception thrown by the WAI time manager.
I will check this today.

**Comment by kazu-yamamoto** [comment]
FYI: https://github.com/yesodweb/wai/issues/1014

**Comment by edsko** [comment]
I tried reverting ef79679 but I'm still seeing this happening.

**Comment by kazu-yamamoto** [comment]
This is very strange.

- `TimeoutThread` cab be thrown if `registerKillThread` is used.
- `registerKillThread` is used only in `withTimeout`.
- `withTimeout` is used inside of `forkManaged` which ignores all exceptions.

@edsko Are you using WAI timeout manger in your client side by yourself?

**Comment by kazu-yamamoto** [comment]
I pushed c8453f6 which explicitly catches `TimeoutThread` in `withTimeout` according to rule 2 in https://github.com/yesodweb/wai/issues/1014.

**Comment by edsko** [comment]
We initialize the WAI time manager, because the `http2` config wants it, but don't otherwise use it. I tried with c8453f6 but no difference. I think the issue is more subtle. I will continue to dig and let you know.

**Comment by edsko** [comment]
Ok, have confirmed that we can deal with this our side. I will close this issue.

**Comment by kazu-yamamoto** [comment]
`withTimeout` is now using `T.withHandleKillThread` which ignores `KillThread`.
So, if @edsko's analysis is correct, this issue should not happen v5.3.7.

**Comment by kazu-yamamoto** [comment]
> We previously had some logic (#136, #137)  to avoid this race condition, but I guess this logic has now been removed. 

Even with the current code, `cancel` is called before throwing `KilledByHttp2ThreadManager`.
So, I don't understand why this race happens yet.

**Comment by edsko** [comment]
I think the race condition is gone as of the refactoring that uses `time-manager-0.2`.
