### ISSUE TITLE
Test suite failure for http2-3.0.0     spec:  executable not found

### ISSUE THREAD

**Issue by juhp** [kazu-yamamoto/http2#22]
When building http2-3.0.0 for Stackage Nightly, we hit:
```
Test suite failure for package http2-3.0.0
    spec:  executable not found
```

**Comment by juhp** [comment]
I am assuming this may be https://github.com/bitprophet/spec ?
Unfortunately didn't find it packaged in Ubuntu (though it is in Fedora).

**Comment by kazu-yamamoto** [comment]
`spec` in `http2` means `hspec`. I don't know why this happens.

**Comment by juhp** [comment]
Ah I see: would it help to add hspec or something also to the Build-Tools-Depends?
I am not that familiar with hspec.

**Comment by kazu-yamamoto** [comment]
It has:

```
  Build-Tool-Depends:   hspec-discover:hspec-discover
```

**Comment by kazu-yamamoto** [comment]
Closing.
Please reopen if necessary.
