### ISSUE TITLE
Allow TLS config to be supplied to https clients

### ISSUE THREAD

**Issue by ProofOfKeags** [kazu-yamamoto/http2#25]
In many gRPC use cases (which is my primary use for http2), you want to specify additional root CA certificates. Currently `Network.HTTP2.Client` does not allow this.

It seems like the approach would be to supply the http client with https://hackage.haskell.org/package/tls-1.5.5/docs/Network-TLS.html#t:ClientParams

**Comment by kazu-yamamoto** [comment]
`http2` does not depend on `tls`. You can pass a TLS connection through `Config`.

If you want to have a wrapper function like `allocTLSConfig`, I should consider implementing it.

**Comment by ProofOfKeags** [comment]
Noted. Thank you.

**Comment by edsko** [comment]
See also https://github.com/kazu-yamamoto/http2/issues/36#issuecomment-1600535791 .
