### ISSUE TITLE
Question: do client/server implementations detect half-open/dead TCP connections?

### ISSUE THREAD

**Issue by ProofOfKeags** [kazu-yamamoto/http2#26]
I'm considering migrating the http2-grpc library to using this as an underlying transport mechanism but wanted to know if it would solve the main problem I have with it presently which is to detect dead TCP connections and throw exceptions as a result.

**Comment by kazu-yamamoto** [comment]
Basically speaking, the only way to detect dead TCP is use `send` or related syscalls. An HTTP/2 connection in `http2` consists of multiple threads but luckily `sender` is the main thread. So, the detection should be possible but I don't confirm it. Even if such a mechanism is missing, it should be easily implemented.
