### ISSUE TITLE
Executable imposes a lower bound on `aeson` in Stackage

### ISSUE THREAD

**Issue by jkachmar** [kazu-yamamoto/http2#35]
Just noticed this when going to build LTS-18.24; it seems like the `http2` client executable is built by default, which means that it imposes a bound on `aeson`:

```
aeson-1.5.6.0 ([changelog](http://hackage.haskell.org/package/aeson-1.5.6.0/changelog)) (Adam Bergmark <adam@bergmark.nl> @bergmark) is out of bounds for:
- [ ] http2-3.0.3 (>=2). Grandfathered dependencies. @kazu-yamamoto. Used by: executable
```

I think it might be possible to gate this behind a build flag that defaults to disabling the executable component (which would prevent Stackage from trying to construct a build plan). If that's reasonable I could try to open a PR with it.

**Comment by kazu-yamamoto** [comment]
To build `client`, you need to specify `-f devel` to cabal. But yes, the `hpack` command is the source of this issue. Do you want to try fixing this issue and send a PR? Or, should I just do it?

**Comment by kazu-yamamoto** [comment]
Closing.
Please reopen if necessary.
