### ISSUE TITLE
[Limitaion] sendRequest function passed to the client is NOT thread-safe – it cannot be called concurrently

### ISSUE THREAD

**Issue by epoberezkin** [kazu-yamamoto/http2#37]
That is, can it be used concurrently from multiple threads?

Or should there be something that queues calls to it, like reads/writes to TCP handle?

I've actually already implemented a queueing mechanism, and now just feeling a bit stupid as from looking at source code it does look thread safe, and queueing requests just makes performance worse...

**Comment by epoberezkin** [comment]
@kazu-yamamoto this is a real issue - this function is not thread safe and cannot be used concurrently.

I currently use queueing that makes sure there are no concurrent calls to this function, but probably it should be thread safe given how API is designed.

**Comment by kazu-yamamoto** [comment]
I guess this was fixed in a76cdf3.
If you can use `sendRequest` concurrently with `master`, please close this issue.

**Comment by epoberezkin** [comment]
will test that!

**Comment by kazu-yamamoto** [comment]
Closing.
Please reopen if necessary.
