### ISSUE TITLE
responseBodySize always returns Nothing

### ISSUE THREAD

**Issue by epoberezkin** [kazu-yamamoto/http2#38]
Even when response has a body.

**Comment by epoberezkin** [comment]
Specifically, that happens with Apple APNS service, and when I print the headers table I do not see content-size there, so maybe Apple simply doesn't send it...

**Comment by epoberezkin** [comment]
requestBodySize in HTTP2 server also returns Nothing...

**Comment by kazu-yamamoto** [comment]
`requestBodySize` in the server side returns Just only when the response body is created from a file.
For streaming data, it's not possible to know the entire size in advance.

**Comment by epoberezkin** [comment]
Thank you!

But if I pass a bytestring that I do know the size in advance - why cannot it set the response size? Or should I manually set the header for it in this case?

**Comment by kazu-yamamoto** [comment]
The `responseFoo` families come from WAI.
`responseByteString` is not provided.
`responseBuilder` takes a `Builder` whose size is unknown.
I'm not sure but you could set Content-Length before you convert `ByteString` to `Builder`.

**Comment by kazu-yamamoto** [comment]
Added d715db1ce4a46b18aed0ea540d2b51f53d8486ba.

**Comment by kazu-yamamoto** [comment]
This test fails. Uhhhhm. Yes, a bug exists.

**Comment by kazu-yamamoto** [comment]
I'm closing this.
