### ISSUE TITLE
Client requestStreaming does not work? / any way to put file and additional data in request body

### ISSUE THREAD

**Issue by epoberezkin** [kazu-yamamoto/http2#40]
From looking at the code, I am not sure if it is implemented?

A simple example of client I have never calls streaming function...

```
  H.requestStreaming N.methodPost "/" [] $ \sendChunk done -> do
    sendChunk $ byteString t
    forM_ filePath_ $ \path -> withFile path ReadMode sendFile
    done
    where
      sendFile h =
        B.hGet h blockSize >>= \case
          "" -> pure ()
          bs -> sendChunk (byteString bs) >> sendFile h
```

Possibly I am doing something stupid here?

The reason I don't want to use filespec as I want to put additional data in the body...

I've also tried to use requestBuilder with lazy bytestring to include both the data and the file, but it seems to try to put too much data in the frame – the server cannot process it (specifically, one of the received chunks includes "exceeds maximum frame size" in this case).

**Comment by kazu-yamamoto** [comment]
Your code looks good.
Let's add your code to the test cases and see what happens.

> the server cannot process it (specifically, one of the received chunks includes "exceeds maximum frame size" in this case).

Is this the case for a client in Haskell and an open server (in another language)?

**Comment by kazu-yamamoto** [comment]
7be47f7 should fix this bug.
However, this reveals another bug in the client side, sigh.

**Comment by epoberezkin** [comment]
> Is this the case for a client in Haskell and an open server (in another language)?

nope, both use this library. I just printed what was on the wire...

**Comment by epoberezkin** [comment]
> https://github.com/kazu-yamamoto/http2/commit/7be47f7aa3b7a9bc8d305a5805d714746891743e should fix this bug.

excellent, will try it now

**Comment by epoberezkin** [comment]
Please ping here once released if you can, I will switch from commit to the latest version.

**Comment by kazu-yamamoto** [comment]
I'm closing this.
