### ISSUE TITLE
Haddock failure: Network/HTTP2/Server/Types.hs:33:5: error: parse error on input ‘}’

### ISSUE THREAD

**Issue by runeksvendsen** [kazu-yamamoto/http2#42]
I get the following error when building haddocks:

```
Network/HTTP2/Server/Types.hs:33:5: error: parse error on input ‘}’
   |
33 |     }
   |     ^
```

Caused by this line: https://github.com/kazu-yamamoto/http2/blob/136188cdf4c2d750f3f8ac780a7be4b33b36d12d/Network/HTTP2/Server/Types.hs#L32

**Comment by kazu-yamamoto** [comment]
To record your credit, PR is welcome!

**Comment by runeksvendsen** [comment]
@kazu-yamamoto done

**Comment by kazu-yamamoto** [comment]
Thanks!
