### ISSUE TITLE
duplicated contents in streaming

### ISSUE THREAD

**Issue by kazu-yamamoto** [kazu-yamamoto/http2#49]
`cabal test` sometime fails:

```
  test/HTTP2/ServerSpec.hs:39:9: 
  1) HTTP2.Server.server handles normal cases
       uncaught exception: IOException of type ResourceVanished
       Network.Socket.sendBuf: resource vanished (Broken pipe)
```

1. The server sends `ConnectionErrorIsSent ProtocolError 1768910346 "stream id should be odd`.

2. The client tries to send GOAWAY or somting and got `Network.Socket.sendBuf: resource vanished (Broken pipe)`.

1768910346 comes from `client3''` of repeated `'t'`. This means that the contents is parsed as an HTTP/2 header.
`tcpdump` says that the contents is duplicated.

So, the streaming implementation has a bug.

We need to check 2., too.

Cc: @epoberezkin

**Comment by epoberezkin** [comment]
I did have an issue that on long leaving connections, that have multiple streaming requests with large bodies, at first the performance deteriorates and then it is stalled (client hangs on receiving response). I worked around this by re-setting connection on timeout errors, so it works for now - but it's interesting if it's related.
