### ISSUE TITLE
Client does not respect the SETTINGS_MAX_CONCURRENT_STREAMS

### ISSUE THREAD

**Issue by akshaymankar** [kazu-yamamoto/http2#71]
Currently there is no check in the client about exceeding maximum concurrent streams, when testing by using this library as the server, the server sends a `RST_STREAM` on the stream which causes the max streams to exceed the configured number (100). The client should either block for the creation of a new stream or throw an error to the consumer.

**Comment by kazu-yamamoto** [comment]
You are right. I need to think how to implement it.

**Comment by kazu-yamamoto** [comment]
This has been implemented on `master`.
But I don't know how to test it at this moment.

**Comment by akshaymankar** [comment]
I wrote this test, it seems to work:

```
        it "respects max concurrent streams setting" $
            E.bracket (forkIO $ runServer irresponsiveServer) killThread $ \_ -> do
                threadDelay 10000
                let maxConcurrentStreams = 64

                resultVars <- runClient "http" "localhost" $ \sendReq -> do
                    for [1..(maxConcurrentStreams + 1) :: Int] $ \_ -> do
                        resultVar <- newEmptyMVar
                        concurrentClient resultVar sendReq
                        pure resultVar

                let acceptedRequestVars = take maxConcurrentStreams resultVars
                acceptedResults <- for acceptedRequestVars (timeout 1000000 . takeMVar)
                for_ acceptedResults $ \case
                    Nothing -> expectationFailure "Exception was not raised"
                    Just (Left ConnectionIsClosed) -> return ()
                    Just (Left err) -> expectationFailure $ "Raise unexpected exception " ++ show err
                    Just (Right ()) -> expectationFailure "Unexpected client termination"

                let waitingRequestVars = drop maxConcurrentStreams resultVars
                waitingResults <- for waitingRequestVars (timeout 1000000 . takeMVar)
                for_ waitingResults $ \case
                    Nothing -> pure ()
                    Just (Left err) -> expectationFailure $ "Raise unexpected exception " ++ show err
                    Just (Right ()) -> expectationFailure "Unexpected client termination"
```

It would be great if there is visibility about how many streams are running or whether and not a request is going to wait at the client side. This can help making decisions like perhaps creating another connection to a different server or throttling the number of requests being made.

**Comment by kazu-yamamoto** [comment]
Great!
I added this test case to `master` with your credit.

I will prepare the API very soon.
Note that the current `master` requires https://github.com/kazu-yamamoto/network-control which is not released yet.

**Comment by kazu-yamamoto** [comment]
I think this issue is resolved.
