### ISSUE TITLE
Bug in `sendRequest`?

### ISSUE THREAD

**Issue by edsko** [kazu-yamamoto/http2#73]
It's entirely possible I just misunderstand, but I _think_ there is a bug in [`sendRequest`](https://github.com/kazu-yamamoto/http2/blob/a41dd7415d0dcdfe4e40f989fecb91d4c254f6f0/Network/HTTP2/Client/Run.hs#L76):

```haskell
let setup = addMyId mgr
let teardown _ = deleteMyId mgr
E.bracket setup teardown $ \_ -> void $ forkIO $ do
  ..
```

(this was introduced in #47). The call to `forkIO` will return immediately, so that call to `teardown` will happen immediately.

**Comment by kazu-yamamoto** [comment]
I guess that `setup` and `teardown` should move into the inside of `forkIO`.
If you agree, would you send a PR?

**Comment by edsko** [comment]
Yes, I think at least the `teardown` should move inside. Will send a PR.

**Comment by kazu-yamamoto** [comment]
`forkFinally` would be nice.

**Comment by edsko** [comment]
Yes, I actually introduced `forkManaged :: Manager -> IO () -> IO ()` in my WIP branch. Just figuring out one detail at the moment, will submit a PR soon.

**Comment by edsko** [comment]
PR at #74.
