### ISSUE TITLE
`RST_STREAM` with `NO_ERROR` should not throw `StreamErrorIsReceived`

### ISSUE THREAD

**Issue by edsko** [kazu-yamamoto/http2#76]
Let me try to describe the issue from first principles. First, some relevant sections of the HTTP2 specification:

[Section 6.4](https://datatracker.ietf.org/doc/html/rfc7540#section-6.4):

> The `RST_STREAM` frame (`type=0x3`) allows for immediate termination of a stream.  `RST_STREAM` is sent to request cancellation of a stream _or_ to indicate that an error condition has occurred.

(my emphasis). Then, just to be complete, [Section 7](https://datatracker.ietf.org/doc/html/rfc7540#section-7):

> NO_ERROR (0x0):  The associated condition is not a result of an error.  

And most importantly, [Section 8.1](https://datatracker.ietf.org/doc/html/rfc7540#section-8.1):

> An HTTP response is complete after the server sends -- or the client receives -- a frame with the END_STREAM flag set (including any CONTINUATION frames needed to complete a header block).  A server can send a complete response prior to the client sending an entire request if the response does not depend on any portion of the request that has not been sent and received.  When this is true, a server MAY request that the client abort transmission of a request without error by sending a RST_STREAM with an error code of NO_ERROR after sending a complete response (i.e., a frame with the END_STREAM flag). Clients MUST NOT discard responses as a result of receiving such a RST_STREAM, though clients can always discard responses at their discretion for other reasons.

In my use case (I am writing a new gRPC client library based on `http2`), this is important, because gRPC servers make use of this option to close a stream in certain cases (some relevant tickets: https://github.com/grpc/grpc-java/issues/2162, https://trac.nginx.org/test/ticket/1792). 

However, in `http2`, when the client receives a `RST_STREAM`, [it will throw a `StreamErrorIsReceived` exception](https://github.com/kazu-yamamoto/http2/blob/3aa161e8386e4fff62251178160ff50eced84607/Network/HTTP2/Arch/Receiver.hs#L439-L443). 
I _think_ that it is not possible to catch this exception (at least, in a useful way) in client code:

* The exception is thrown in the [`frameReceiver`](https://github.com/kazu-yamamoto/http2/blob/3aa161e8386e4fff62251178160ff50eced84607/Network/HTTP2/Client/Run.hs#L32), which is a background thread spawned by `http2`
* [It is _caught_ there too](https://github.com/kazu-yamamoto/http2/blob/3aa161e8386e4fff62251178160ff50eced84607/Network/HTTP2/Arch/Receiver.hs#L82-L85), causing the client to send a `GOAWAY` frame to the server
* It is then [rethrown by `frameSender`](https://github.com/kazu-yamamoto/http2/blob/master/Network/HTTP2/Arch/Sender.hs#L108), which is [another background thread](https://github.com/kazu-yamamoto/http2/blob/3aa161e8386e4fff62251178160ff50eced84607/Network/HTTP2/Client/Run.hs#L33). 
* This then causes the backgrounds thread to terminate, which [in turn terminates the client](https://github.com/kazu-yamamoto/http2/blob/3aa161e8386e4fff62251178160ff50eced84607/Network/HTTP2/Client/Run.hs#L41).

None of this is under the control of the client. 

What I think should happen instead is that no exception is thrown at all when the client receives `RST_STREAM` with `NO_ERROR` as its error code; instead, the stream should simply be closed, and that's it. 

@kazu-yamamoto If you agree with this analysis, let me know, and I can try to submit a PR. (If you have any suggestions on what the fix should look like, let me know that too :) ).

**Comment by kazu-yamamoto** [comment]
You are 100% right. Please send a PR!
