### ISSUE TITLE
`GOAWAY` frame can overtake final `DATA` frame

### ISSUE THREAD

**Issue by edsko** [kazu-yamamoto/http2#87]
(This is the corrected issue from #86 ).

I was getting non-deterministic test failures in my test suite. I think it's because when the client sends the final message to the server and then disconnects, there is a race condition between the final `DATA` frame and the `GOAWAY` frame. Successful test run:

![image](https://github.com/kazu-yamamoto/http2/assets/935288/be4f764a-3db1-4821-b687-6fa7de82f656)

(The client is sending the value "4" before disconnecting). 

Failing test run:

![image](https://github.com/kazu-yamamoto/http2/assets/935288/4a8858a4-76b3-4404-b7b1-5af062ccb240)
![image](https://github.com/kazu-yamamoto/http2/assets/935288/ca657e06-e4f8-44d2-b0ca-49cd0445c926)

This is the exact same test, but the frame ordering has been reversed: since the server sees the `GOAWAY` frame _first_, it never receives the client's final message.

_Possibly_ related: #78.

I am currently using a (rather nasty) workaround by having  a `threadDelay 1_000` before closing the connection and after sending the final message.

**Comment by kazu-yamamoto** [comment]
We should ensure that all threads for streaming (spawned with `forkManaged`) are finished after `x <- client $ ...` and before `let frame = goawayFrame`.
An easy way to implement this is provide an STM counter and `check (cnt == 0)`.

**Comment by kazu-yamamoto** [comment]
Goaway data should hold `MVar` and the client should `takeMVar` after putting it into the queue.
Sender should `putMVar` after sending.
I will take care of this next week.
Have a good weekend.

**Comment by edsko** [comment]
Fantastic, thanks @kazu-yamamoto :) I can check after ICFP if your patch fixes my test cases.
